var setupInfo = { "setupInfo" : [
{ "HOME_0IN" : "C:/QFT_2021.1/QFT_2021.1/QFT/V2021.1/win64" },{ "QHOME" : "C:/QFT_2021.1/QFT_2021.1/QFT/V2021.1/win64" },{ "ZSH" : "" },{ "ZI_RTLD_LIB" : "" }]};
var category = { "category" : [
{ "categoryId" : "0" , "categoryName":"Rtl Design Style" },
{ "categoryId" : "1" , "categoryName":"Simulation" },
{ "categoryId" : "2" , "categoryName":"Synthesis" },
{ "categoryId" : "3" , "categoryName":"Connectivity" },
{ "categoryId" : "4" , "categoryName":"Reset" },
{ "categoryId" : "5" , "categoryName":"Clock" },
{ "categoryId" : "6" , "categoryName":"Testbench" },
{ "categoryId" : "7" , "categoryName":"Nomenclature Style" },
{ "categoryId" : "8" , "categoryName":"Setup Checks" }]};
var severity = { "severity" : [
{ "severityId" : "0" , "severityName":"Error" },
{ "severityId" : "1" , "severityName":"Warning" },
{ "severityId" : "2" , "severityName":"Info" }]};
var statusObj = { "status" : [
{ "statusId" : "0" , "statusName":"uninspected" },
{ "statusId" : "1" , "statusName":"pending" },
{ "statusId" : "2" , "statusName":"waived" },
{ "statusId" : "3" , "statusName":"bug" },
{ "statusId" : "4" , "statusName":"fixed" },
{ "statusId" : "5" , "statusName":"verified" }]} ;
var checks = { "checks":[
{ "checksId":"0", "checksName":"assign_width_underflow","severityId":"0","categoryId":"0"},
{ "checksId":"1", "checksName":"if_else_if_can_be_case","severityId":"2","categoryId":"0"},
{ "checksId":"2", "checksName":"unconnected_inst_output","severityId":"1","categoryId":"3"},
{ "checksId":"3", "checksName":"inst_port_width_mismatch","severityId":"0","categoryId":"0"},
{ "checksId":"4", "checksName":"reserved_keyword","severityId":"2","categoryId":"7"},
{ "checksId":"5", "checksName":"multi_driven_signal","severityId":"0","categoryId":"1"},
{ "checksId":"6", "checksName":"part_select_illegal","severityId":"0","categoryId":"0"},
{ "checksId":"7", "checksName":"seq_block_first_stmt_not_if","severityId":"0","categoryId":"4"},
{ "checksId":"8", "checksName":"flop_without_control","severityId":"2","categoryId":"4"},
{ "checksId":"9", "checksName":"always_has_inconsistent_async_control","severityId":"1","categoryId":"4"},
{ "checksId":"10", "checksName":"array_index_with_expr","severityId":"0","categoryId":"0"},
{ "checksId":"11", "checksName":"identifier_with_error_warning","severityId":"2","categoryId":"7"},
{ "checksId":"12", "checksName":"fsm_without_one_hot_encoding","severityId":"2","categoryId":"0"},
{ "checksId":"13", "checksName":"always_signal_assign_large","severityId":"1","categoryId":"0"},
{ "checksId":"14", "checksName":"parameter_name_duplicate","severityId":"2","categoryId":"7"},
{ "checksId":"15", "checksName":"comment_not_in_english","severityId":"2","categoryId":"7"},
{ "checksId":"16", "checksName":" ","severityId":"3","categoryId":"9"}]};
var schematicStatus = {  
"assign_width_underflow" : "off",
"if_else_if_can_be_case" : "off",
"unconnected_inst_output" : "on",
"inst_port_width_mismatch" : "off",
"reserved_keyword" : "off",
"multi_driven_signal" : "on",
"part_select_illegal" : "off",
"seq_block_first_stmt_not_if" : "off",
"flop_without_control" : "on",
"always_has_inconsistent_async_control" : "off",
"array_index_with_expr" : "off",
"identifier_with_error_warning" : "off",
"fsm_without_one_hot_encoding" : "off",
"always_signal_assign_large" : "off",
"parameter_name_duplicate" : "off",
"comment_not_in_english" : "off"};
var adaptiveModeStatus = {  
"assign_width_underflow" : "off",
"if_else_if_can_be_case" : "off",
"unconnected_inst_output" : "off",
"inst_port_width_mismatch" : "on",
"reserved_keyword" : "off",
"multi_driven_signal" : "off",
"part_select_illegal" : "off",
"seq_block_first_stmt_not_if" : "off",
"flop_without_control" : "on",
"always_has_inconsistent_async_control" : "off",
"array_index_with_expr" : "off",
"identifier_with_error_warning" : "off",
"fsm_without_one_hot_encoding" : "off",
"always_signal_assign_large" : "off",
"parameter_name_duplicate" : "on",
"comment_not_in_english" : "off"};
var checkAliasMap = { };
var argMap = {  
"1":"lhs_expression",
"2":"lhs_width",
"3":"rhs_width",
"4":"module",
"5":"file",
"6":"line",
"7":"port",
"8":"instance",
"9":"signal",
"10":"argument_width",
"11":"formal_width",
"12":"master_file",
"13":"master_line",
"14":"name",
"15":"reason",
"16":"expression",
"17":"declaration_file",
"18":"declaration_line",
"19":"line1",
"20":"flop1",
"21":"flop2",
"22":"line2",
"23":"array",
"24":"count",
"25":"limit",
"26":"parameter",
"27":"module1",
"28":"file1",
"29":"module2",
"30":"file2"};
